import {
  ib,
  cq,
  qf,
  c,
  ffz,
  js,
  cpp,
  python,
  html,
  css,
  scss,
  react,
  rn,
  tail,
  nativeW,
  chakra,
  bootstrap,
  figma,
  node,
  express,
  appWrite,
  mongo,
  mysql,
  vs,
  idea,
  insomnia,
  postman,
  canva,
} from "../assets/index";

export const ProjectCardData = [
  {
    img: ib,
    title: "InsightBlaze",
    desc: "",
    git: "https://github.com/Shasatya/Insight-Blaze",
    site: "",
    used: ["MongoDB", "Express.js", "React", "Node.js"],
    id: 1,
  },
  {
    img: cq,
    title: "CoinQuake",
    desc: "",
    git: "https://github.com/Shasatya/CoinQuake",
    site: "https://coin-quake.vercel.app/",
    used: ["React", "Chakra UI", "Coingecko-Api"],
    id: 2,
  },
  {
    img: cq,
    title: "Satyam's Portfolio",
    desc: "",
    git: "https://github.com/Shasatya/CoinQuake",
    site: "https://coin-quake.vercel.app/",
    used: ["React", "Saas"],
    id: 3,
  },
  {
    img: cq,
    title: "Nike",
    desc: "",
    git: "https://github.com/Shasatya/CoinQuake",
    site: "https://coin-quake.vercel.app/",
    used: ["React", "Tailwind CSS"],
    id: 4,
  },
  {
    img: qf,
    title: "Quickfix",
    desc: "",
    git: "https://github.com/Shasatya/Quickfix",
    site: "https://quickfix-ochre.vercel.app/",
    used: ["React", "Saas"],
    id: 5,
  },
  {
    img: c,
    title: "Complify",
    desc: "",
    git: "https://github.com/Shasatya/complify",
    site: "https://complify.vercel.app/",
    used: ["HTML", "CSS", "JavaScript"],
    id: 6,
  },
  {
    img: ffz,
    title: "FeastFinderz",
    desc: "",
    git: "https://github.com/Shasatya/feast-finderz",
    site: "https://feast-finderz.vercel.app/",
    used: ["HTML", "CSS", "JavaScript"],
    id: 7,
  },
];

export const NavListData = [
  {
    id: 1,
    label: "Home",
    href: "home",
  },
  {
    id: 2,
    label: "Stack",
    href: "stack",
  },
  {
    id: 3,
    label: "Projects",
    href: "projects",
  },
  {
    id: 4,
    label: "Contact",
    href: "contact",
  },
];

export const StackData = [
  {
    key: 1,
    title: "Programming Languages",
    icons: [js, cpp, python],
  },
  {
    key: 2,
    title: "Front-End",
    icons: [
      html,
      css,
      scss,
      react,
      rn,
      tail,
      nativeW,
      chakra,
      bootstrap,
      figma,
    ],
  },
  {
    key: 3,
    title: "Back-End",
    icons: [node, express, appWrite],
  },
  {
    key: 4,
    title: "Database Management",
    icons: [mongo, mysql],
  },
  {
    key: 5,
    title: "Tools",
    icons: [vs, idea, insomnia, postman, canva],
  },
];
